name: Build and Deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ec2-3-83-161-204.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "build/"
          target: "/react"