name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: andres64372
          password: dckr_pat_ffCIuoZAdWn-DJkKMnVUm14OP2Q
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            HOST=http://localhost/api
          tags: andres64372/aeroptimal:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Deployment on instance
        run: |
          cd /home/ubuntu
          docker compose pull aeroptimal
          docker compose up --no-deps -d aeroptimal
          docker image prune -f